name = "backend"
compatibility_date = "2024-08-14"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGRiYWM4NzItMDI2NC00NmE5LWE3MjAtMzdmOGExMjNiZTM4IiwidGVuYW50X2lkIjoiMTJiMGFjMjM5YjU2MTc1YmEwMzY1YTlkOGVjZWMxOWY4YzdjNDc1OGUxNjg0ZTgzZmZmOWM3MTRhZjc4ZTE5MiIsImludGVybmFsX3NlY3JldCI6ImUzNzUzOTZiLWQ1MTItNDA5ZS04MzQxLWU2NjAxZjAyNTBkZiJ9.IqnhGFoA2rlfhJBXl_PllNUTIk1s22TqQMx2KIkNFDo"
JWT_SECRET = "asdsdsds"
